"""Add hyperlinks column to CV model

Revision ID: 20291f822f47
Revises: ca4c6b2cccb8
Create Date: 2025-04-12 14:02:43.473832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20291f822f47'
down_revision = 'ca4c6b2cccb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hyperlinks', sa.Text(), nullable=True))

    with op.batch_alter_table('job_description', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_description', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.drop_column('hyperlinks')

    # ### end Alembic commands ###
