"""Add generated_resume column to CV

Revision ID: a3ed1f9f6507
Revises: 20291f822f47
Create Date: 2025-04-13 20:40:17.794277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ed1f9f6507'
down_revision = '20291f822f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generated_resume', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.drop_column('generated_resume')

    # ### end Alembic commands ###
